apiVersion: apps/v1
kind: Deployment
metadata:
  name: unblu-visitor-sso-sample
spec:
  selector:
    matchLabels:
      app: unblu-visitor-sso-sample
  template:
    metadata:
      labels:
        app: unblu-visitor-sso-sample
    spec:
      containers:
        - name: jwt-auth
          image: unblu-visitor-sso-sample
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          envFrom:
            - configMapRef:
                name: sample-jwt-auth-config
