resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: sample-jwt-auth-config
    literals:
      - UNBLU_SERVERURL=https://example.unblu.cloud

images:
  - name: unblu-visitor-sso-sample
    newName: ghcr.io/unblu/unblu-visitor-sso-sample
    newTag: latest
