name: Build and publish
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Java 1.8 and run tests
        run: ./gradlew build test
      - uses: actions/upload-artifact@v2
        with:
          name: Application JAR
          path: build/libs
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Java 11 and run tests
        run: ./gradlew clean build test
  publish:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: ./gradlew bootBuildImage --imageName=unblu-visitor-sso-sample
      - name: Tag and push image
        run: |
          docker tag unblu-visitor-sso-sample ghcr.io/unblu/unblu-visitor-sso-sample
          docker tag unblu-visitor-sso-sample ghcr.io/unblu/unblu-visitor-sso-sample:${GITHUB_SHA::8}
          docker push ghcr.io/unblu/unblu-visitor-sso-sample
          docker push ghcr.io/unblu/unblu-visitor-sso-sample:${GITHUB_SHA::8}

