name: Build and Deploy Docs
on: [ push ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          sudo apt update
          sudo apt install -y ruby
          gem install asciidoctor rouge
          asciidoctor -o docs/index.html documentation.adoc

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: docs
          folder: docs
